/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://37tnmw2rb5byti6tmbul7l5u3m.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dqhpkfhzojezrf5ng42h2nykxu",
    "aws_cognito_identity_pool_id": "ap-southeast-1:573c8854-9620-40e3-a5bd-a41ebd40b635",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_BQw8m8Kwp",
    "aws_user_pools_web_client_id": "j5cqeppm28801683eb20p9810",
    "oauth": {}
};


export default awsmobile;
